# Generated by Django 5.0.2 on 2024-03-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testuser',
            name='name',
            field=models.CharField(default=None, max_length=150, unique=True),
        ),
    ]
