# Generated by Django 5.0.2 on 2024-03-03 19:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_squashed_0002_alter_testuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testuser',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID'),
        ),
    ]
