# Generated by Django 5.0.2 on 2024-03-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_testuser_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='testuser',
            name='remember_token_expiration',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
