# Generated by Django 5.0.2 on 2024-03-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_testuser_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testuser',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
