# Generated by Django 5.0.2 on 2024-03-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_testuser_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='testuser',
            name='article',
            field=models.JSONField(null=True),
        ),
    ]
