# Generated by Django 5.0.2 on 2024-03-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_testuser_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testuser',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
